# Site settings
title: Nikki Stevens
email: nikki.stevens@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  Nikki Stevens is an open-source software engineer and PhD student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nikkistevens.com" # the base hostname & protocol for your site
twitter_username: drnikki
github_username:  drnikki

paginate: 10

# Build settings
markdown: kramdown
keep_files: ['assets']
# System stuff
timezone: America/Los_Angeles

gems:
- jekyll-redirect-from

plugins:
- jekyll-paginate
- jekyll-sitemap

# https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles
permalink: :title
