# Site settings
title: Nikki Stevens
email: nikkilstevens@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nikki Stevens is an open-source software engineer and PhD student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.drnikki.org" # the base hostname & protocol for your site
twitter_username: drnikki
github_username:  drnikki

paginate: 10

# Build settings
markdown: kramdown
keep_files: ['assets']
# System stuff
timezone: America/Los_Angeles

gems:
- jekyll-redirect-from
- jekyll-paginate-v2


# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
